fix: Updated IOT-dev-guide URLs in /public/help.
bonitoo-io/iot-center-v2 pull request #36
Opened 2021-05-04 22:17 UTC by jstirnaman

Fixes #

## Proposed Changes

_Briefly describe your proposed changes:_

## Checklist

- [x] Rebased/mergeable
- [x] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

2021-05-05 01:39 UTC, sranka requested changes
LGTM except for one URL. Thank you for improving the docs.

2021-05-05 01:39 UTC, sranka commented on app/ui/public/help/DashboardPage.md
> +For more, see the [_InfluxDB IoT dev guide_](https://influxdata.github.io/iot-dev-guide/dashboard.html).
```suggestion
For more, see the [_InfluxDB IoT dev guide_](https://influxdata.github.io/iot-dev-guide/ui/dashboard.html).
```

2021-05-05 13:36 UTC, jstirnaman commented on app/ui/public/help/DashboardPage.md
> +For more, see the [_InfluxDB IoT dev guide_](https://influxdata.github.io/iot-dev-guide/dashboard.html).
@sranka Fixed. Thanks - thought I tested them all.

2021-05-12 14:32 UTC, jstirnaman commented
Hi, @sranka, could you review this again please?

2021-05-12 14:43 UTC, sranka approved these changes

2021-05-12 14:44 UTC, merged